os:
  - osx
before_install:
  - brew install python --force
  - pip2 install numpy
  - pip2 install scipy
  - pip2 install requests
  - pip2 install scikit-learn
  - pip2 install pytest
install:
  - pip2 install -e .
script: py.test tests/
